### ISSUE TITLE
您好，智能计算系统

### ISSUE THREAD

**Issue by huanghonggit** [Pengwei-Jin/subconverter_ini#1]
您好，最近在学智能计算系统...能学习下您智能计算系统 YOLOv3的实验代码嘛

**Comment by Pengwei-Jin** [comment]
YOLOv3那个实验我没做。（三选一的实验）你可以在[寒武纪开发者论坛](http://forum.cambricon.com/)里面搜索相关的帖子。

**Comment by huanghonggit** [comment]
您好,我找遍了也没有关于那个yolov3实验的帖子，能加您微信聊嘛...

**Comment by Pengwei-Jin** [comment]
我只看见[这个帖子](http://forum.cambricon.com/show-3-688-1.html)。而且课程实验据说会大改

**Comment by huanghonggit** [comment]
谢谢...YOLO实验主要是实现nms_detection.h&nbsp; 没找着这个...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pengwei-Jin/subconverter_ini"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月28日(星期三) 晚上7:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Pengwei-Jin/subconverter_ini] 您好，智能计算系统 (#1)





 
我只看见这个帖子。而且课程实验据说会大改
